/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 room.glb --transform
Author: Anex (https://sketchfab.com/anex)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/room-6417cbc1870a4a1691cca06912ae0369
Title: Room
*/

import { Html, useGLTF } from "@react-three/drei"
import { useEffect, useRef } from "react"
import ScreenData from "./screen"
import "./styles.css"

export function Model(props) {
  const { nodes, materials } = useGLTF("/room-transformed.glb")

  materials.podloga.map = null
  materials.sciana_okno.map = null
  console.log(nodes)

  const floor = useRef()

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.Material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials["Material.002"]} />
        <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials["Material.003"]} />
        <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} position={[-6, 0, -0.45]} scale={0.7} material={materials.krzeslo_1} />

        <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} position={[6, 0, -0.45]} scale={0.7} material={materials.krzeslo_prawe} />
        <mesh position={[0, 10, 6]}>
          <boxGeometry args={[14, 1, 10]} />
          <meshStandardMaterial color={"black"} />
          <Html rotation={[Math.PI / 2, 0, 0]} position={[0, -2, -0.7]} className="content" transform occlude>
            <ScreenData />
          </Html>
        </mesh>
        <mesh receiveShadow geometry={nodes.Object_10.geometry} material={materials.podloga} ref={floor} />
        <mesh castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials.sciana_okno} />
        <mesh castShadow receiveShadow geometry={nodes.Object_14.geometry}>
          <meshStandardMaterial color={"black"} />
        </mesh>
        <mesh castShadow receiveShadow position={[0, 7, 0]} geometry={nodes.Object_15.geometry} material={materials["Material.005"]} />
      </group>
    </group>
  )
}

useGLTF.preload("/room-transformed.glb")
